### ISSUE TITLE
Battery is not supported

### ISSUE THREAD

**Issue by nicman23** [burzumishi/linux-baytrail-flexx10#11]
but there is progress: https://bugzilla.kernel.org/show_bug.cgi?id=88471

**Comment by ghost** [comment]
I have a Flexx 9, not a 10, so I don't know if the instructions on this page are generic or not or from some similar device, but the HW uses the axp288_\* kernel modules for hardware monitoring, the maa8425 for spatial positioning and the jsa1212 for ambient light sensing.  The camera on the Flexx 9 is the OVTI2680 which may be different between these models, but I'm willing to bet the other sensors are the same.

The kernel has support for all this hardware with the exception of the camera, but like the LKML link indicates, they don't work properly yet on our hardware (input voltage gives a reading but it looks like a fictitious number).

**Comment by nicman23** [comment]
For me it just says that there is no battery, when I cat anything from /sys/class/

**Comment by ghost** [comment]
<i>https://github.com/Icenowy/axpd</i>

This workaround for battery status works for me (tm)...

**Comment by ghost** [comment]
Some more good news -- enable all the AXP2\* modules in the kernel, and now Bluetooth works, at least on 4.8.  It certainly never did on any earlier kernel.

**Comment by ghost** [comment]
Specifically, the modules in question seem to be axp20x and axp20x_i2c.  With these loaded, the start_bt.sh script fires up the Bluetooth and I can see my phone.

Hint and credit go to a post on the rtl8723bs_bt forum where some pin states dealing with BT were manipulated though the AXP i2c interface.

**Comment by nicman23** [comment]
Nice. We just need better wifi performance and s3 and lower state and it will finally be usable. 

Btw did you ever get pulse to work without the scripts that state alsa?

**Comment by ghost** [comment]
Audio here is working 100% with the exception of the speaker/headphone muting and the mic (haven't played with these yet).  You have to initially bootstrap the ALSA mixer, but your init scripts should save the mixer states across reboots.  The reason being, those scripts in /usr/lib/alsa aren't perfect for our exact mixer configuration, so pulse is doing the master volume through software mixing. 

Now, are you able to get Kernel Modesetting working on the i915?  This is my **big** problem (no accelerated video).  I also don't any any C/P-state issues, but I suspect these are linked to i915 and why they haven't bit me yet.

The network performance is really, really good on 4.8 now that the sdhci patches are upstream - you just need this one patch and you're golden - https://github.com/hadess/rtl8723bs/files/379444/0001-My-changes-for-4.7.0-rc7-for-Baytrail-T.patch.txt

**Comment by nicman23** [comment]
Thanks for all of your work !

Really do not have the time to tinker right now and I do really appreciate your testing and help.

About alsa yes I know that I do not have to rerun the scripts, I was wondering about automatically switching from headsets to speakers.

For modesetting, want problem are you having? You want to use modesetting for X? I think, didn't have any reason to test it, that it used i915. Ttys were working fine and startx didn't read any errors. Does GLAMOR say that is not supported?

About the s states, I meant better suspend support and adding instant2go sleep that is so good on windows.

**Comment by ghost** [comment]
Gotcha.  I'm pretty confident I know how to get the rest of ALSA/pulse working (device switching), it's just a little labor-intensive due to the number of mixer controls this thing presents, but I do need the headphone to work so it's up on my priority list.

As for modesetting, I'm getting the classical blank screen when the i915 loads.  This is presumably due to lack of proper MIPI DSI support for this panel (at least in the Flexx 9).  You can load X, but it's on top of any of the unaccelerated framebuffer devices.

S/states, I haven't even tried to suspend the machine.

**Comment by ghost** [comment]
It would be really, really helpful, whenever you get a chance (no rush!!), to post your dmesg up to the point that your X server loads, with "options drm debug=12" set.  This way, I can see how the panel _should_ be detected and used.  I know how the Asus and the Dell tablets should work, but not these.

**Comment by nicman23** [comment]
Yes OK. I might be able today. 

X and kms always worked for my machine, but again it is a different model with mostly the same bios and internals.

Might be distro or .config dependant?

**Comment by ghost** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=82880 ( <- that's exactly what my problem appears to be).  Could also be PEBKAC.  I don't think it's the distro, as it happens in the i915 kernel module (from k.org), not X.

I suspect it's a firmware problem, as i915 is detecting the build-in panel as VGA-1.  I think it should be DSI-1.

**Comment by burzumishi** [comment]
You're right "xrandr" shows it up as DSI-1 in my device, and i915_drm module is loaded.

Have you tried to change GRUB_GFX_PAYLOAD=keep and GRUB_GFXMODE="your device resolution" in /etc/default/grub?

I'll post my dmesg while X server is loading with "options drm debug=12" set up.

**Comment by nicman23** [comment]
yeah i ll do that today about 10 pm utc+3

**Comment by burzumishi** [comment]
I've attached my files to KMS issue: https://github.com/burzumishi/linux-baytrail-flexx10/issues/8

**Comment by RussianNeuroMancer** [comment]
There is update at https://bugzilla.kernel.org/show_bug.cgi?id=88471

AXP288 patch published: https://bugzilla.kernel.org/attachment.cgi?id=245031

**Comment by ghost** [comment]
Outstanding!!  Thank you.

**Comment by ghost** [comment]
I can confirm this is working.  You have to manually load some of the kernel modules as stated in the last post: https://bugzilla.kernel.org/show_bug.cgi?id=88471

You also need to blacklist the 'battery' kernel module.

Minor fix for 4.9 kernels: http://home.ix.netcom.com/~jjingber/0020-axp288_power_monitoring.patch

**Comment by nicman23** [comment]
nice will close when patch is documented.

**Comment by RussianNeuroMancer** [comment]
Turns out this patch from my previous comment was insufficient - battery info read once on boot and then doesn't updated anymore. Additional change is required: http://4pda.ru/forum/index.php?showtopic=650808&view=findpost&p=55252765 
Also there is other change needed to hide not-existing battery: https://github.com/sfumato77/Kernel-4.8_Android-x86_BayTrail/commit/e8e70e9722bb7a83d6ee29bc660c393885f47bd1 (three diffs above). Without it two batteries will be detected even if there is really only one.

**Comment by ghost** [comment]
Thank you.  It is updating here, however.

**Comment by RussianNeuroMancer** [comment]
It's updating for you with 4.8 or 4.9?

**Comment by youling257** [comment]
i must need to know Charging current, discharge current ， i must use https://github.com/zhaofengli/iwork8/blob/master/scripts/battery.sh ，thanks for zhaofengli .

**Comment by youling257** [comment]
Since Ubuntu support for reading multiple batteries ，why don't use two and more battery ? i must use /sys/class/power_supply/test_battery、axp288_fuel_gauge，BMBT，remove BMBT，only for Status bar battery icon can display the state of charge and discharge、display capacity .
solve battery_BMBT/intel sr1/sr real battery is the right way，test_battery、axp288_fuel_gauge are opportunistic

**Comment by youling257** [comment]
modified:drivers/acpi/ac.c，modified:drivers/acpi/battery.c，modified:drivers/acpi/scan.c，just for Android healthd，https://groups.google.com/d/msg/android-x86/9gLesRMykzw/VRs2Lw8yBQAJ

**Comment by ghost** [comment]
Well, I spoke to soon.

The /sys entries work (/sys/class/power_supply/axp288_fuel_gauge/capacity), but user-space tools don't seem to pick this up.  

Also, user-space won't detect removal of the AC adapter if the axp* kernel modules are loaded when the adapter is present.

At the moment, the axpd script works while this really doesn't.

**Comment by ghost** [comment]
The /sys entries work so I don't know why user space tools are being fussy with this.

**Comment by youling257** [comment]
just use https://bugzilla.kernel.org/attachment.cgi?id=245691 ! 
don't use https://bugzilla.kernel.org/attachment.cgi?id=245031 and https://bugzilla.kernel.org/attachment.cgi?id=245211

**Comment by ghost** [comment]
That patch doesn't really work either --

The meter starts at 95%, and bounces up an down to nonsensical values (ie.  it'll go from 83% to 88% while on battery).

As ugly as it is, the script still works better.

**Comment by RussianNeuroMancer** [comment]
Yep, previous one https://github.com/burzumishi/linux-baytrail-flexx10/issues/11#issuecomment-261558368 https://github.com/burzumishi/linux-baytrail-flexx10/issues/11#issuecomment-261760373 works better for me too.

Packages is here: https://yadi.sk/d/pW1Fbl-VyVPoR (4.8.10 rev1).

**Comment by Tuxman2** [comment]
Hello Guys,

well, what is it safe or not safe in the patches for Audio, Battery, Backlight and others things at Baytrail hardware ? 
You gave a link for an axp288 patch but it can break the hardware (it says USE AT YOUR OWN RISK). I'm ready to test the patches but I don't want to break my hardware.

Thanks.

@RussianNeuroMancer: I don't know if it is your packages in the link above, but if you compile the packages for Ubuntu with kernel mainline PPA patches, can you tell me how you did it (what are the commands to use for make the right compilation) ? And if I use the kernel mainline PPA patches, must I apply them before or after applying the patches given here (audio, backlight, ...) ? Thanks. I downloaded the source code from Kernel Mainline PPA Ubuntu.

**Comment by nicman23** [comment]
audio and backlight, yes. battery i do not know, but the worst it could 
happen is a kernel panic or that the tablet shuts off because it is out 
of battery and the script did not work :P.

take care that you do follow the audio instructions to the letter (see 
later posts in the respective issue), because if you are stupid (like me 
for example) you may kill your speaker.

**Comment by Tuxman2** [comment]
@nicman23: I'm happy that the community found a solution for Baytrail Audio card. I don't know who use an Ubuntu or similar distribution here (I think youling257 and RussianNeuroMancer). Well, it is a pity that the Baytrail hardware doesn't work totally 'out-of-the-box' for now. We must always check the compatibility of the hardware with Linux, while under Windows, it works without problem. Fortunately, the Linux community is still there to solve the problems. Do you put a how-to here when the final kernel 4.9 is released ? (to know what are changes must be made to the kernel (patches for example) or not).

About the battery, mine is named sr1 real battery under the desktop.

**Comment by nicman23** [comment]
> while under Windows, it works without problem

Lol nope

Also yes we will update this for 4.9 and this is not Ubuntu or debian instructions. We (I) try to keep it distribution agnostic.

**Comment by Haxk20** [comment]
mine only says battery even the i2c script is not working for me idk if i need anything in kernel config like the AXP288 i think i need this but still those patches and things i hate them because update comes and again you miss new stuff and need to comile again will be happy if ubuntu enable it as default

**Comment by RussianNeuroMancer** [comment]
@Tuxman2
Fetch source code: git clone -b 'v4.8.12' --single-branch --depth 1 git://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack 
Download relevant Canonical patches for same release: http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.8.12/

Apply patches (run this in mainline-crack folder)
```
for file in /patch/to/mainline-crack/*.patch
do
    patch -p1 < "$file"
done
```

Disable zfs in debian.master/rules.d/amd64.mk
Copy files from debian.master to debian folder. Rename debian/control.stub.in to debian/control.
chmod +x debian/rules
chmod -R 700 debian/scripts
chmod -R 700 debian/scripts/misc
fakeroot debian/rules clean
fakeroot debian/rules editconfigs
Change kernel options (use / for search) or load config file by placing it into build folder.
Pay attention to options I mentioned in Readme: https://yadi.sk/d/pW1Fbl-VyVPoR
Then build kernel and headers packages: fakeroot debian/rules binary-headers binary-generic

> while under Windows, it works without problem

At least on my tablet suspend was broken in Windows 10 for a year, until Intel fixed it and make wakeup reliable (my tablet used to hang on wakeup very frequently, like every 2nd/3rd time I wake it up). I not talking about many other issues, like camera drivers that incompatible with fast boot mode, RTC clocks that sometimes doesn't wake up tablet (possible due to RTC IRQ issue) very buggy video drivers, etc.

**Comment by Tuxman2** [comment]
@RussianNeuroMancer: Thanks. ;-)
I'm waiting the final version of 4.9 kernel who will be available in the 2 or 3 days (I hope).
About patches, must I apply all patches (available here and the mainline patches from Ubuntu kernel ppa ) at the same time ?
Is the make oldconfig, make menuconfig and make clean commands are necessary or not after fakeroot debian/rules editconfigs command ?
In my case, I use the 32 bit version because I have problem with the 64 bit version.

Regards.

**Comment by RussianNeuroMancer** [comment]
@Tuxman2
> must I apply all patches (available here and the mainline patches from Ubuntu kernel ppa ) at the same time ?
I apply patches in order that you can see in Readme.txt

Is the make oldconfig, make menuconfig and make clean commands are necessary or not after fakeroot debian/rules editconfigs command ?
Just  fakeroot debian/rules editconfigs is enough.

**Comment by Tuxman2** [comment]
@RussianNeuroMancer: Ok. I will try when the final 4.9 kernel will be available. ;-)

**Comment by Tuxman2** [comment]
Hello,

@RussianNeuroMancer: I saw informations about debian rules methods on the net.
 It seems that if we want to use our config file (from the previous kernel), we must copy this file to /debian/config/amd64 or /debian/config/i386/  and then run these commands: 
fakeroot debian/rules clean
debian/rules updateconfigs or fakeroot debian/rules updateconfigs

See it: http://blog.avirtualhome.com/compile-mainline-kernel-ubuntu/  (Creating a new config).
If we are applying patches, updateconfigs command seems to be necessary.

About kernel build command, we can add skipabi=true to skip ABI checks. I don't know if the AUTOBUILD=1 option is necessary and if we must specify DEB_BUILD_OPTIONS=parallel=x (x is the number of processor/cores the hardware can use for the compilation). This last command can speed up the compilation.
With these options, the kernel build line must be like that:  DEB_BUILD_OPTIONS=parallel=4 AUTOBUILD=1 skipabi=true fakeroot debian/rules binary-headers binary-generic

Is the binary-perarch option must be added ?

What do you think about it ?

**Comment by RussianNeuroMancer** [comment]
@Tuxman2 
> It seems that if we want to use our config file (from the previous kernel), we must copy this file

To /debian/config/amd64, /debian/config/i386/ or /build, all ways probably will works, but I tested only /build way.

> I don't know if the AUTOBUILD=1 option is necessary
> Is the binary-perarch option must be added ?

Works for me without it.

> if we must specify DEB_BUILD_OPTIONS=parallel=x (x is the number of processor/cores the hardware can use for the compilation)

Nope, building with fakeroot debian/rules binary-headers binary-generic utilize all cores without this variable.

**Comment by Tuxman2** [comment]
@RussianNeuroMancer: Ok. ;-) I guess you don't use the skipabi=true option anymore ?

@ALL: Good news !!! Final kernel version 4.9 is out (4.9 is now stable). Now we must know what patches can be used or not. :-)

Regards.

**Comment by RussianNeuroMancer** [comment]
> I guess you don't use the skipabi=true option anymore ?

Never used it, never heard about it before.

**Comment by Tuxman2** [comment]
@RussianNeuroMancer: As the stable 4.9 kernel is out now. I guess you will give informations like you did for 4.8.xx kernel (see your readme.txt file) ?

**Comment by RussianNeuroMancer** [comment]
@Tuxman2, probably, but not soon for sure. When - it's depend on all people who write/adjust all this patches.

**Comment by Tuxman2** [comment]
Hello,

@RussianNeuroMancer: I forgot to ask you a question the last time. I will use the configuration file of my old kernel (4.4.x) on the new kernel 4.9.x. You told me to put this file (.config I guess) in the /build folder. OK. But as you know, my old configuration file needs to be updated with the latest version of the kernel. With the old method, we put the old kernel configuration file at the root of the kernel source folder, then we use the make oldconfig command, and the make menuconfig command. How does it works with Debian scripts? As you said we must put the old configuration file in /build folder, but then do we use the fakeroot debian/rules updateconfigs and fakeroot debian/rules editconfigs commands? It is this part that I don't quite understand.

Thank you for the clarification and your help. ;-)

**Comment by Tuxman2** [comment]
Hi,

I see that 4.8.0-30.32 kernel is available in the Ubuntu repositories. 4.8.0-30.32 kernel sources are also available. If I want to use that kernel version or create a custom kernel from that version, do I need to apply your patches on 4.8.0-30.32 kernel sources (clocksource patch for audio, axp288 patches for battery, patches for backlight, ...) ? Is it easy to compile kernel source file from Ubuntu repositories ?

Thanks.

**Comment by RussianNeuroMancer** [comment]
@Tuxman2 

> my old configuration file needs to be updated with the latest version of the kernel

Do this manually in fakeroot debian/rules editconfigs or save config, edit it, load edited config.

**Comment by Tuxman2** [comment]
@RussianNeuroMancer: ok, but I would have preferred to do it automatically.
Could you provide all the necessary patches files in this link: https://yadi.sk/d/pW1Fbl-VyVPoR ?
You gave the links in your readme.txt but it is not easy to download them.

Thanks in advance.

**Comment by ghost** [comment]
RussianNeuroMancer patches are working for me (I tested for awhile before I opened my mouth this time).

Thank you.

**Comment by ghost** [comment]
This may make it easier than going through this whole thread.  Tested on 4.9:

http://home.ix.netcom.com/~jjingber/0020-axp288_power_monitoring.patch
http://home.ix.netcom.com/~jjingber/0022-hide_phantom_batteries.patch

**Comment by youling257** [comment]
can't open it http://home.ix.netcom.com/~jjingber

**Comment by ghost** [comment]
<i>can't open it http://home.ix.netcom.com/~jjingber</i>

Sorry -- should work now!!  Thank you.

**Comment by ghost** [comment]
youling ^-- actually these seem to be based on your patches.  They weren't working on 4.8 but that are working on 4.9.

**Comment by Tuxman2** [comment]
I think I will use the official kernel sources from Ubuntu (for now, it is 4.8.0-34) and apply your custom patches on it. I will preferred waiting for the 4.9 kernel later. Thanks to RussianNeuroMancer to give the patches links in his own readme.txt file but it doesn't help me because it is not .patch files.
Can you tell me what patches must I apply if I want to use the kernel sources 4.8.0-34 from Ubuntu ?

Thanks.

**Comment by ghost** [comment]
The clock source patch is not a requirement.  If you enable MCLK_EN, then you need the patch.  

Frankly, this seems to be confusing a lot of people here (based on all the clock-related posts) and is not necessary for audio and is completely unrelated to the RTC.

**Comment by nicman23** [comment]
Can you explain what the MCLK_EN is?

**Comment by ghost** [comment]
That's just the constant that enables the audio driver to use the Baytrail platform clock patch.  It's unnecessary and confusing.

**Comment by Tuxman2** [comment]
It will be great if someone here could make a summary on what to apply as modifications/patches for 4.8 kernel and 4.9 kernel (to make a custom kernel) in order to operate our devices.  There is so much information in the different messages that we are lost.

Thanks.

**Comment by nicman23** [comment]
http://mailman.alsa-project.org/pipermail/alsa-devel/2016-December/115886.html

relevant

**Comment by Haxk20** [comment]
Guys is there some patch for 4.8 that can make battery status visible ?

**Comment by Haxk20** [comment]
Or i should upgrade to 4.9 and apply the patches above because on 4.8 they hide my battery completely

**Comment by nicman23** [comment]
Sorry, i would but i am deep into finals atm + forgotten my charger on 
my uni dorm...

if someone wants to post anything like that, shout at me and i ll edit 
the readme.md

**Comment by Haxk20** [comment]
Ok fixed it and battery status is fully showed and working with the patches above and config from this repo 4.8.0-rc2 and added few configs related to axp288 and battery from  https://yadi.sk/d/pW1Fbl-VyVPoR thanks to RussianNeuroMancer for creating the README and after compiling and building the kernel its working and it add support for power button too

**Comment by Haxk20** [comment]
And its at kernel 4.8.13-1 Arch linux

**Comment by Tuxman2** [comment]
@Haxk20: It seems that you use Ubuntu like me. Can you tell me what are the correct patches (battery, sound, backlight, c-state, ...) that I must apply to 4.8.0.x kernel on Ubuntu because there are a lot of patches from here and from the RussianNeuroMancer README. Have you tried to apply the custom patches to the official 4.8.0.x kernel from Ubuntu ?

Thanks.

**Comment by Haxk20** [comment]
no is use arch linux for battery just use the patches from RussianNeuroMancer and CONFIGS from README too from RussianNeuroMancer the for backlight still not working but i dont care about BL sound not working too but i will aplly clocksource patches for sound and lets see what will happen then C-state this doesnt require patch to work just look at another issue from me refering to it i explain it in there then power button use config from README too its SOC_ARRAY or something like that then sound buttons there is patch for it too i think its in this repo thats all but if you know i need to fix the clocksource issue for me because i use jiffies for now but wifi is not working with it  refined-jiffies is just slowing down and tsc wifi is working but after that clocksource is unstable and make unexpected rx frames cannot time with tsc and actually cannot do anything with tsc i found patch for something like that but failed apllying it dont know why if you know some patch that can make tsc to work i will be really happy

**Comment by jusss** [comment]
may I ask how you shut down your linux system? I have to shut it down with power-off physical key

**Comment by Haxk20** [comment]
Normally trough gui or if you are in cli use poweroff now

**Comment by Tuxman2** [comment]
Hi,

It's been quite a while that we don't have information on Baytrail hardware support with the new kernels (4.9.x and 4.10-rcx) here. The latest information was about 4.8.x and lower kernels. I would like to help this community but for this I need to know what patches are necessary or not for the recent kernels. I recovered the kernel 4.9.5 because the kernel 4.10 is always in RC. Can any of you provide a list of fixes to apply on 4.9.x kernels and future kernel 4.10.x for Baytrail ? As well as the elements to be used (parameters, files, ...) to operate the hardware (sound card, battery, ....).

If necessary I can help you to find informations.

Thanks.

**Comment by RussianNeuroMancer** [comment]
Personally I will wait for 4.11, when AXP288 patches by Hans de Goede will get upstreamed. Sound stuff seems like getting into upstream too: https://github.com/torvalds/linux/commits/master/sound/soc/intel/boards/bytcr_rt5640.c (as you see upstream now include commits from Pierre repository).
Clock driver still not merged unfortunately:
https://patchwork.kernel.org/patch/9277989/
https://github.com/torvalds/linux/tree/master/drivers/clk/x86

**Comment by Tuxman2** [comment]
@RussianNeuroMancer: Thanks for your reply. :-)

The 4.11 kernel will not be available before many months. As I see, for the sound, it will be working 'out of the box' with the 4.10 kernel (but the Add Atom PMC platform clocks patch is still necessary, as well as the UCM files). Do you think the quirk table patch for sound will be always needed with the 4.10 kernel ? Well, as you said the axp288 patches will be upstream in 4.11 kernel, then it means that those patches will be always necessary in 4.10 kernel.
For c-state problem, for now it is a pain, the Linux community try to find a solution but it is not easy (they've got patches but it doesn't work with all the kernels mostly with the new kernels 4.9.x).

I guess that it is a good idea to wait for the 4.10 kernel final version rather then using the 4.9.x kernel, isn't it ? Or try the 4.10-rc5 kernel for now ?

If others people have informations, thanks to share. ;-)

Note: For stabilize the RTL8723BS driver, a solution is available here: https://github.com/hadess/rtl8723bs/issues/76 (in the end of the discussion). And another, here: https://github.com/hadess/rtl8723bs/issues/80

**Comment by Tuxman2** [comment]
@RussianNeuroMancer: I would like to try your custom kernel (4.8.10) from here: https://yadi.sk/d/pW1Fbl-VyVPoR/Linux%204.8/Linux%204.8.10
As I don't have the same hardware as yours (yours is DEXP Ursus 7W, mine is Medion Akoya) , is there a risk that my hardware can be broken ? What is the best choice: rev1 or rev2 ? I guess that your custom kernel files have all the necessary patches to make work the Baytrail hardware (sound, battery, ...) ? What do I need as files to make work sound with your custom kernel ? What should I pay attention to ?

Thanks for your reply.

Note: I want to tell to all people here that the Baytrail rt5640 sound hardware will be full supported in the 4.11 kernel.

**Comment by RussianNeuroMancer** [comment]
@Tuxman2 

> is there a risk that my hardware can be broken ? 

Anything can broke this hardware I guess. I seen reports that for example Chiwu Hi12 get bricked by Windows updates intended for Teclast but because of some Microsoft mistake get delivered on Chuwi Hi12. Also people talk that disabling cameras or accelerometer in Windows Device Manager could bricks this tablet. And obviously changing some BIOS setting could lead to brick or unbootable device.

So, if you doesn't know how to unbrick your tablet with chip programmer, any other OS besides preinstalled OS with disabled updates, could be dangereous, including GNU/Linux. But this is just disclaimer, in my opinion only real danger of using GNU/Linux was for BayTrail devices with audio in PCI mode (instead of i1c mode) with wrong configuration file (that intended for another devices) that lead to burned speaker, besides this I doesn't seen reports about hardware damages by GNU/Linux (at least yet).

> What is the best choice: rev1 or rev2 ? I

You have to find out yourself. For me rev1 works better on one devices, and rev2 works better on another. Only difference between rev1 and rev2 is AXP288 driver (check Readme.txt) so you have to pay attention to "acpi -V" output.

> I guess that your custom kernel files have all the necessary patches to make work the Baytrail hardware (sound, battery, ...) ? 

Yes, but don't forget about UCM files.

> What should I pay attention to ?

To Readme.txt and UCM files. You also could install tlp to increase battery life, disable Akonadi (or remove akonadi-server) and Baloo in KDE case, or disable Gnome Software and Gnome Tracker autostart in Gnome Shell case (to free memory) and use Opera in permanent battery saving mode (don't forget to enable hardware rendering on GPU and double check this is working)

> Note: I want to tell to all people here that the Baytrail rt5640 sound hardware will be full supported in the 4.11 kernel.

I hope that https://www.spinics.net/lists/platform-driver-x86/msg10311.html will get merged too.

**Comment by Tuxman2** [comment]
@RussianNeuroMancer: Thanks for your remarks.

I will try to make a custom kernel for my hardware by using your readme.txt file and one of the 4.8.x kernel source (probably the last). If it doesn't work, I will try your deb packages. 

I have some questions about your readme.txt file.

1. Well, I see 4.8-fixes patchset (0014-0038). Does it means that I must apply patchset from 0014 to 0038 ? 

2. I guess that I must apply a patch for quirk table problem. In your readme, you talked about IN1 changed to IN3. How I must know what IN number I must apply for my hardware ? I don't know if I must define IN1 or IN3 or other thing ? Do I need the Baytrail platform clock patch ? 

3. I don't need silead patch and backlight patch (backlight works out of the box on my hardware). What is the purpose of the tsc=reliable force_tsc_stable=1 clocksource=tsc clocksource_failover=tsc line in the GRUB_CMDLINE_LINUX option ?

I should not have too many problems with the other patches (axp288, burzumishi patches) and kernel options, shown in your readme.

Regards.

Note: I put some informations for my Baytrail sound hardware in the 'Possible progress on the audio' topic (in the end).
I have some difficulties with the debian/rules. I would like to know if I can use first the old method (copy my .config file to source folder, use make oldconfig and make menuconfig) and then use the debian/rules to compile sources (fakeroot debian/rules clean, fakeroot debian/rules binary-headers binary-generic).

**Comment by RussianNeuroMancer** [comment]
> Does it means that I must apply patchset from 0014 to 0038 ?

Yes.

> How I must know what IN number I must apply for my hardware ?

Check if it works with IN1, and if it's doesn't - then IN3.

> Do I need the Baytrail platform clock patch ?

Yes.

> What is the purpose of the tsc=reliable force_tsc_stable=1 clocksource=tsc clocksource_failover=tsc line in the GRUB_CMDLINE_LINUX option ?

With refined-jiffies clocksource instead of tsc you will get freezes. Linux on BayTrail not always choice tsc on boot, so it's good idea to force tsc use and nothing else.

**Comment by Tuxman2** [comment]
@RussianNeuroMancer: Thanks.

I will try the compilation next week. ;-)
If I have problems I will post here.

I would like to ask you one last thing. You used a 4.8.xx kernel but can we use all the patches described in your readme with the 4.9.xx kernel sources or the 4.10 kernel sources ?

**Comment by RussianNeuroMancer** [comment]
No. I will see what still needed for 4.11, hopefully not much (at least audio and battery stuff should be completely merged upstream by then).

**Comment by Tuxman2** [comment]
Ok, then, I will use a 4.8.xx kernel until the 4.11 kernel will be out. 4.10 kernel final release is near but 4.11 kernel final release will not be available before two months.
Hopefully the machines will have full support before the end of this year.

**Comment by Tuxman2** [comment]
@RussianNeuroMancer:

Well, I compiled a custom 4.8.xx kernel by using your all informations from your readme.txt file (patches, routing patches, ...). I didn't use the debian/rules like you said to me, but I used the make-kpkg command. I've got a linux-image file and a linux-headers file. Now I've got some questions:

1. Do I need the fw_sst_0f28_ssp0.bin file to /usr/lib/firmware and must made a symlink to fw_sst_0f28.bin ? It is the solution given by jharrison022. I installed the UCM files. I also want to know if I must blacklist snd_soc_sst_acpi for enable snd_intel_sst_acpi module ?

2. For battery, do I need to apply this tip ? :

2.1 /etc/modules-load.d/axp288.conf
extcon-core
extcon-axp288
axp288_adc
axp20x_usb_power
axp288_charger
axp20x-regulator
axp288_fuel_gauge
2.2 battery in /etc/modprobe.d/blacklist.conf

3. I must compile the driver for WIFI and Bluetooth (RTL8723BS). Do I need the driver from Hadess (from here: https://github.com/hadess/rtl8723bs) ? How to make Bluetooth work ?

4. Is there any optimisation to made for our Baytrail hardware ?

Thanks.

**Comment by RussianNeuroMancer** [comment]
>  I didn't use the debian/rules like you said to me, but I used the make-kpkg command. 

IMO it's better to build deb packages.

> Do I need the fw_sst_0f28_ssp0.bin file to /usr/lib/firmware and must made a symlink to fw_sst_0f28.bin ? 

I never do that. 

> I also want to know if I must blacklist snd_soc_sst_acpi for enable snd_intel_sst_acpi module ?

This is not actual anymore as I remember.

> For battery, do I need to apply this tip ?

Only for rev2 as I remember.

> I must compile the driver for WIFI and Bluetooth (RTL8723BS). 

Follow this: http://www.xkyle.com/building-linux-packages-for-kernel-drivers/

> How to make Bluetooth work ?

Look inside 
rtl8723bs-firmware_0.4-1~xenial1_all.deb here: https://yadi.sk/d/LbaBpYVuqYfCy (check systemd unit file example).

> Is there any optimisation to made for our Baytrail hardware ?

Apply PulseAudio optimizations (in the end of Readme.txt), install tlp, use Opera with always active battery saving feature, disabled GPU blacklist, enabled rasterisation with four threads (in opera://flags).

**Comment by Tuxman2** [comment]
Hi RussianNeuroMancer,

Ok, I will test without symlink and without blacklist the snd_soc_sst_acpi module. I've got the Bluetooth without installing driver but I don't have wifi for this moment. I created a new topic here because I've got a lot of error messages after using dmesg command. Perhaps you could tell me how to solve some of them ? I guess the rtl8723bs-firmware_0.4-1~xenial1_all.deb is for wifi too ?

Thanks.

**Comment by RussianNeuroMancer** [comment]
> I guess the rtl8723bs-firmware_0.4-1~xenial1_all.deb is for wifi too ?

It contain firmware files for WiFi adapter, yes.

**Comment by RussianNeuroMancer** [comment]
@nicman23

Issue is resolved with 4.11rc1, so I guess this bug can be closed now.

**Comment by jusss** [comment]
@RussianNeuroMancer  more details please,  does it need to enable some options and no patches in 4.11rc1?  that will be wonderful!  :-)

**Comment by RussianNeuroMancer** [comment]
@jusss for me it's working out of the box, however you may want to try [this options](https://github.com/burzumishi/linux-baytrail-flexx10/issues/35#issuecomment-286366756) if it won't work for you.

**Comment by nicman23** [comment]
@RussianNeuroMancer Closing thanks , move discussion to #12 :)
